@Library('devops') _
//logs.info 'Starting'
//logs.warning 'Nothing to do!'

pipeline {
    agent none
    stages {
        stage ('Example') {
            steps {

                script {
                    log.info 'Starting'
                    log.warning 'Nothing to do!'
                }
            }
        }
    }
}